import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import { findClientByConfigLinkAcrossServers, findClientBySubIdAcrossServers } from '@/lib/xui';

export const dynamic = 'force-dynamic';

// ==========================================
// GET /api/migration/check?key=<config-link|sub-link|token>
// Looks up an old VPN key and returns its details
// ==========================================

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const key = searchParams.get('key')?.trim();

    if (!key) {
      return NextResponse.json({ error: 'Missing key parameter' }, { status: 400 });
    }

    const configLinkMatch = key.match(/^(vmess|vless|trojan|ss):\/\//i);
    if (configLinkMatch) {
      const panelClient = await findClientByConfigLinkAcrossServers(key);
      if (!panelClient) {
        return NextResponse.json(
          { error: 'Key not found. Please check your config link and try again.' },
          { status: 404 }
        );
      }

      const now = Date.now();
      const expiryTime = panelClient.expiryTime ?? 0;
      const remainingDays = expiryTime > 0 ? Math.max(0, Math.ceil((expiryTime - now) / (24 * 60 * 60 * 1000))) : null;
      const dataLimitGB = panelClient.totalGB ? Number((panelClient.totalGB / 1024 / 1024 / 1024).toFixed(2)) : 0;

      return NextResponse.json({
        success: true,
        message: 'Key found on 3xUI panel via config link. It can be migrated.',
        data: {
          token: key,
          username: panelClient.email || 'Unknown',
          devices: panelClient.limitIp || 1,
          expiryTime,
          remainingDays,
          protocol: panelClient.protocol || 'trojan',
          dataLimitGB,
          keyType: 'panel_only',
          serverId: panelClient.serverId,
          serverName: panelClient.serverName,
        },
      });
    }

    // Extract token: support full sub-link URL (3x-UI `/sub/{id}`) or bare token string
    let token = key;
    const subLinkMatch = key.match(/\/(?:api\/vpn\/)?sub\/([a-zA-Z0-9-]{8,64})/i);
    if (subLinkMatch) {
      token = subLinkMatch[1];
    }

    // Accept alphanumeric subIds generated by 3x-UI or longer hex tokens (UUIDs).
    if (!token || !/^[a-zA-Z0-9-]{8,64}$/i.test(token)) {
      return NextResponse.json(
        { error: 'Invalid key format. Please provide a valid config link, sub-link or token.' },
        { status: 400 }
      );
    }

    const mongoose = await connectDB();
    const db = mongoose.connection.getClient().db();

    const vpnKey = await db.collection('vpn_keys').findOne({ token });

    if (!vpnKey) {
      const panelClient = await findClientBySubIdAcrossServers(token, key);
      if (panelClient) {
        const now = Date.now();
      const expiryTime = panelClient.expiryTime ?? 0;
      const remainingDays = expiryTime > 0 ? Math.max(0, Math.ceil((expiryTime - now) / (24 * 60 * 60 * 1000))) : null;
        const dataLimitGB = panelClient.totalGB ? Number((panelClient.totalGB / 1024 / 1024 / 1024).toFixed(2)) : 0;

        return NextResponse.json({
          success: true,
          message: 'Key found on 3xUI panel but not yet in local DB. It can be migrated.',
          data: {
            token,
            username: panelClient.email || 'Unknown',
            devices: panelClient.limitIp || 1,
            expiryTime,
            remainingDays,
            protocol: panelClient.protocol || 'trojan',
            dataLimitGB,
            keyType: 'panel_only',
            serverId: panelClient.serverId,
            serverName: panelClient.serverName,
          },
        });
      }

      return NextResponse.json(
        { error: 'Key not found. Please check your sub-link and try again.' },
        { status: 404 }
      );
    }

    if (vpnKey.is_migrated) {
      return NextResponse.json(
        { error: 'This key has already been migrated to the new multi-server format.' },
        { status: 409 }
      );
    }

    const now = Date.now();
    const isExpired = vpnKey.expiryTime && now > vpnKey.expiryTime;

    if (isExpired) {
      return NextResponse.json(
        { error: 'This key has already expired and cannot be migrated.' },
        { status: 410 }
      );
    }

    const remainingMs = vpnKey.expiryTime && vpnKey.expiryTime > 1000 ? vpnKey.expiryTime - now : null;
    const remainingDays = remainingMs ? Math.ceil(remainingMs / (24 * 60 * 60 * 1000)) : null;

    return NextResponse.json({
      success: true,
      data: {
        token,
        username: vpnKey.username || 'Unknown',
        devices: vpnKey.devices || 1,
        expiryTime: vpnKey.expiryTime ?? 0,
        remainingDays,
        protocol: vpnKey.protocol || 'trojan',
        dataLimitGB: vpnKey.dataLimitGB || 0,
        keyType: vpnKey.keyType || 'admin_web',
        createdAt: vpnKey.createdAt || null,
      },
    });
  } catch (error) {
    console.error('[migration/check] Error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
