const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '..', 'src', 'lib', 'rotationActions.ts');
let text = fs.readFileSync(filePath, 'utf8');
const regex = /async function inspectRemoteBackup\(host: string, backup: BackupCandidate\): Promise<\{ databaseKind: BackupDatabaseKind; inboundCount: number \}> \{[\s\S]*?return \{ databaseKind: kindMatch\[1\] as BackupDatabaseKind, inboundCount: count \};\r?\n\}/;
if (!regex.test(text)) {
  throw new Error('function block regex not found');
}
const replacement = [
  'async function inspectRemoteBackup(host: string, backup: BackupCandidate): Promise<{ databaseKind: BackupDatabaseKind; inboundCount: number }> {',
  '  let command: string;',
  '',
  '  if (backup.kind === \'postgres\') {',
  '    command = `',
  'set -e',
  'backup=${shellQuote(backup.remotePath)}',
  '[ -s "$backup" ] || { echo "BACKUP_DB_MISSING"; exit 1; }',
  'if ! command -v pg_restore >/dev/null 2>&1; then',
  '  export DEBIAN_FRONTEND=noninteractive',
  '  export NEEDRESTART_MODE=a',
  '  apt-get update -qq',
  '  apt-get install -y -qq postgresql-client >/tmp/bds-pg-client-install.log 2>&1 || { tail -80 /tmp/bds-pg-client-install.log; exit 1; }',
  'fi',
  'pg_restore --data-only --table=inbounds --file=- "$backup" 2>/dev/null | python3 -c \'import sys',
  'count = 0',
  'in_copy = False',
  'for line in sys.stdin:',
  '    if line.startswith("COPY ") and "inbounds" in line:',
  '        in_copy = True',
  '        continue',
  '    if in_copy:',
  '        if line.strip() == "\\." :',
  '            break',
  '        count += 1',
  'print(f"BACKUP_KIND:postgres\\nINBOUND_COUNT:{count}")\'',
  '`;',
  '  } else {',
  '    const archivePrepare = backup.kind === \'archive\'',
  '      ? `',
  'workdir=$(mktemp -d)',
  'cleanup() { rm -rf "$workdir"; }',
  'trap cleanup EXIT',
  'mkdir -p "$workdir"',
  'tar -tzf ${shellQuote(backup.remotePath)} > "$workdir/list.txt"',
  'if grep -qx \'x-ui-postgres.dump\' "$workdir/list.txt"; then',
  '  tar -xzf ${shellQuote(backup.remotePath)} -C "$workdir" x-ui-postgres.dump',
  '  [ -s "$workdir/x-ui-postgres.dump" ] || { echo "BACKUP_DB_MISSING"; exit 1; }',
  '  if ! command -v pg_restore >/dev/null 2>&1; then',
  '    export DEBIAN_FRONTEND=noninteractive',
  '    export NEEDRESTART_MODE=a',
  '    apt-get update -qq',
  '    apt-get install -y -qq postgresql-client >/tmp/bds-pg-client-install.log 2>&1 || { tail -80 /tmp/bds-pg-client-install.log; exit 1; }',
  '  fi',
  '  pg_restore --data-only --table=inbounds --file=- "$workdir/x-ui-postgres.dump" 2>/dev/null | python3 -c \'import sys',
  'count = 0',
  'in_copy = False',
  'for line in sys.stdin:',
  '    if line.startswith("COPY ") and "inbounds" in line:',
  '        in_copy = True',
  '        continue',
  '    if in_copy:',
  '        if line.strip() == "\\." :',
  '            break',
  '        count += 1',
  'print(f"BACKUP_KIND:postgres\\nINBOUND_COUNT:{count}")\'',
  '  exit 0',
  'fi',
  'grep -qx \'etc/x-ui/x-ui.db\' "$workdir/list.txt"',
  'tar -xzf ${shellQuote(backup.remotePath)} -C "$workdir" etc/x-ui/x-ui.db',
  'tar -xzf ${shellQuote(backup.remotePath)} -C "$workdir" etc/x-ui/x-ui.db-wal 2>/dev/null || true',
  'tar -xzf ${shellQuote(backup.remotePath)} -C "$workdir" etc/x-ui/x-ui.db-shm 2>/dev/null || true',
  'db="$workdir/etc/x-ui/x-ui.db"',
  '`',
  '      : `',
  'db=${shellQuote(backup.remotePath)}',
  '`;',
  '',
  '    command = `',
  'set -e',
  '${archivePrepare}',
  '[ -s "$db" ] || { echo "BACKUP_DB_MISSING"; exit 1; }',
  'python3 - "$db" <<\'PY\'',
  'import sqlite3',
  'import sys',
  '',
  'db_path = sys.argv[1]',
  'conn = sqlite3.connect(db_path)',
  'try:',
  '    table_exists = conn.execute(',
  '        "select count(*) from sqlite_master where type=\'table\' and name=\'inbounds\'"',
  '    ).fetchone()[0]',
  '    if not table_exists:',
  '        print("INBOUND_COUNT:0")',
  '        sys.exit(0)',
  '',
  '    count = conn.execute("select count(*) from inbounds").fetchone()[0]',
  '    print(f"BACKUP_KIND:sqlite\\nINBOUND_COUNT:{count}")',
  '    sys.exit(0)',
  'finally:',
  '    conn.close()',
  'PY',
  '`;',
  '  }',
  '',
  '  const output = await execSsh(host, command, 30000);',
  '  const kindMatch = output.match(/BACKUP_KIND:(sqlite|postgres)/);',
  '  const match = output.match(/INBOUND_COUNT:(\d+)/);',
  '  if (!kindMatch || !match) {',
  '    throw new Error(`Could not verify backup database. Output: ${output.slice(0, 300) || '(empty)'}`);',
  '  }',
  '',
  '  const count = Number(match[1]);',
  '  if (count < 1) {',
  '    throw new Error(\'Backup database contains 0 inbounds.\');',
  '  }',
  '',
  '  return { databaseKind: kindMatch[1] as BackupDatabaseKind, inboundCount: count };',
  '}`,
].join('\n');
text = text.replace(regex, replacement);
fs.writeFileSync(filePath, text, 'utf8');
console.log('patched');
